name: Run Test Suite

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Required Tests
    
    services:
      postgres:
        image: postgres:14  
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-xprocess
        pip install playwright pytest-playwright
        playwright install
        
    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Set Up DB
      env:
        PGPASSWORD: postgres
        PGUSER: postgres
      run: |
        createdb -h localhost -U postgres task_manager_test
        
    - name: Run tests
      env:
        DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/task_manager_test"
        PGPASSWORD: postgres
        PGUSER: postgres
      run: |
        python -m pytest